In [111]:
import pandas as pd
import numpy as np
from faker import Faker

In [112]:
## Creating class
fake = Faker()

In [113]:
## Reading files

tr_04_08 = pd.read_csv('../data/transactions_01_06_2025.csv')
tr_11_08 = pd.read_csv('../data/transactions_01_13_2025.csv')
tr_17_08 = pd.read_csv('../data/transactions_01_20_2025.csv')
tr_25_08 = pd.read_csv('../data/transactions_01_27_2025.csv')

## Declaring variables

country_codes = ('UK', 'AU', 'US', 'CA', 'DE')
referral_source_values = (
    "google_ads", "organic",  "social_media",
     "referral", "partner"
)

In [114]:
tr_04_08.columns

Index(['transaction_id', 'transaction_date', 'customer_id', 'product_id',
       'product_name', 'category', 'quantity', 'unit_price', 'total_amount',
       'store_location', 'payment_method'],
      dtype='str')

In [115]:
## Replace it after finishing transformation
## Df for transformation

res_df = pd.concat([
    tr_04_08[['transaction_id']], tr_11_08[['transaction_id']],
    tr_17_08[['transaction_id']], tr_25_08[['transaction_id']]
], ignore_index = True) ## Avoiding ValueError: cannot reindex on an axis with duplicate labels

## Length variable
len_res_df = res_df.shape[0]

In [116]:
## Memory cleaning
del tr_04_08, tr_11_08, tr_17_08, tr_25_08

In [117]:
## Generating names with faker
res_df[['first_name', 'last_name']] = [
    (fake.first_name(), fake.last_name())
    for _ in range(len_res_df)
]

In [118]:
res_df.head()

  transaction_id first_name   last_name
0      TXN000001      Robin     Santana
1      TXN000002    Valerie    Anderson
2      TXN000003  Elizabeth  Livingston
3      TXN000004      Jesse     Roberts
4      TXN000005      James    Jennings

In [119]:
## Generating emails according to name

res_df['email'] = res_df['first_name'].str.lower() + '.'\
                + res_df['last_name'].str.lower() + '@example.com'

In [120]:
## Generating dates with pandas

dates = pd.date_range("2023/06/01", "2024/06/01")
range_1000_2000 = [i for i in range(1000, 2000)]

res_df["signup_date"] = pd.Series(dates).sample(n=len_res_df, replace=True).values
del dates

In [121]:
## Generating user_id

res_df ["user_id"] = np.random.choice(range_1000_2000, size=len_res_df)

del range_1000_2000

res_df["user_id"] = "USR_" + res_df["user_id"].astype("str")

In [122]:
## Generating country and source with numpy

res_df['country'] = np.random.choice(country_codes, size = len_res_df)

In [123]:
## Generating source with numpy (the cheapest way)

res_df['referral_source'] = np.random.choice(referral_source_values, size = len_res_df)

In [124]:
res_df.head()

,transaction_id,first_name,last_name,email,signup_date,user_id,country,referral_source
0,TXN000001,Robin,Santana,robin.santana@example.com,2023-09-24,USR_1752,UK,partner
1,TXN000002,Valerie,Anderson,valerie.anderson@example.com,2024-03-07,USR_1049,UK,partner
2,TXN000003,Elizabeth,Livingston,elizabeth.livingston@example.com,2023-09-16,USR_1304,CA,social_media
3,TXN000004,Jesse,Roberts,jesse.roberts@example.com,2023-08-25,USR_1631,DE,referral
4,TXN000005,James,Jennings,james.jennings@example.com,2024-04-28,USR_1002,AU,partner

In [125]:
## Saving new df

res_df.to_csv(path_or_buf = '../data/users_data.csv', index = False)