In [20]:
import pandas as pd
import numpy as np
from faker import Faker
import random

In [2]:
fake = Faker()

In [3]:
tr_04_08 = pd.read_csv('../seeds/input_data/transaction_04_08_2025.csv')
tr_11_08 = pd.read_csv('../seeds/input_data/transaction_11_08_2025.csv')
tr_17_08 = pd.read_csv('../seeds/input_data/transaction_17_08_2025.csv')
tr_25_08 = pd.read_csv('../seeds/input_data/transaction_25_08_2025.csv')

country_codes = ('UK', 'AU', 'US', 'CA', 'DE')

In [4]:
all_files_df = pd.concat([
    tr_04_08, tr_11_08,
    tr_17_08, tr_25_08
])

## Replace it after finishing transformation

# all_files_df = pd.concat([
#     tr_04_08['user_id'], tr_11_08['user_id'],
#     tr_17_08['user_id'], tr_25_08['user_id']
# ])

In [5]:
all_files_df

,transaction_id,sender_account_id,receiver_account_id,transaction_amount,transaction_timestamp,transaction_type,payment_channel,merchant_category,transaction_status,currency,...,recipient_verified,recipient_account_age_days,recipient_country,latitude,longitude,city,country,ip_country,RecipientGNNScore,is_fraud
0,TXN000000062,ACC0044877,ACC0108626,3355.25,05/08/2025 22:47,P2M,Debit Card,Utilities,Success,INR,...,1,3439,India,17.386227,78.481575,Hyderabad,India,India,NaN,0
1,TXN000000145,ACC0113978,ACC0070986,360.68,07/08/2025 09:20,P2P,UPI,Shopping,Success,INR,...,1,973,India,13.099636,80.267209,Chennai,India,India,NaN,0
2,TXN000000195,ACC0051949,ACC0003579,890.78,09/08/2025 12:02,P2M,UPI,Utilities,Success,INR,...,1,1912,India,23.027151,72.581682,Ahmedabad,India,India,NaN,0
3,TXN000000218,ACC0017916,ACC0044510,3571.38,08/08/2025 23:15,P2P,RTGS,Salary,Success,INR,...,1,727,India,18.513034,73.864665,Pune,India,India,NaN,0
4,TXN000000224,ACC0012180,ACC0025048,4771.63,08/08/2025 07:09,P2M,NEFT,Restaurant,Success,INR,...,1,1771,India,18.525395,73.846750,Pune,India,India,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130,TXN000014485,ACC0024885,ACC0016230,26099.03,25/08/2025 13:43,P2P,UPI,Education,Success,INR,...,1,1368,India,23.013735,72.555939,Ahmedabad,India,India,NaN,0
131,TXN000014502,ACC0007350,ACC0050308,2293.36,27/08/2025 13:46,P2M,UPI,Travel,Success,INR,...,1,55,India,22.560527,88.360011,Kolkata,India,India,NaN,0
132,TXN000014531,ACC0123404,ACC0110706,354.73,31/08/2025 02:44,P2P,UPI,Fuel,Success,INR,...,1,2217,India,12.972258,77.600591,Bengaluru,India,India,NaN,0
133,TXN000014577,ACC0097102,ACC0095593,2694.47,31/08/2025 14:19,Bank Transfer,UPI,Travel,Success,INR,...,1,2808,India,22.585450,88.357444,Kolkata,India,India,NaN,0
134,TXN000014675,ACC0062280,ACC0007726,1194.78,26/08/2025 00:21,P2M,UPI,Healthcare,Success,INR,...,1,2422,India,19.088194,72.874121,Mumbai,India,India,NaN,0

In [6]:
res_df = (all_files_df[['user_id']]
          .sort_values(by = 'user_id', ascending = True))

In [7]:
res_df['first_name'] = [fake.first_name() for _ in range(len(res_df))]

In [8]:
res_df[['first_name', 'last_name']] = [
    (fake.first_name(), fake.last_name())
    for _ in range(len(res_df))
]

In [9]:
res_df.head()

       user_id first_name last_name
79   USR000120    Deborah   Richard
183  USR000336    Deborah      Long
58   USR000756        Amy    Fisher
16   USR000761    Matthew  Trujillo
137  USR000872       Mary   Edwards

In [10]:
res_df['email'] = res_df['first_name'].str.lower() + '.'\
                   + res_df['last_name'].str.lower() + '@example.com'

In [17]:
res_df['country'] = [random.choice(country_codes) for _ in range(len(res_df))]

In [19]:
res_df.head()

       user_id first_name last_name                         email country
79   USR000120    Deborah   Richard   deborah.richard@example.com      CA
183  USR000336    Deborah      Long      deborah.long@example.com      DE
58   USR000756        Amy    Fisher        amy.fisher@example.com      AU
16   USR000761    Matthew  Trujillo  matthew.trujillo@example.com      DE
137  USR000872       Mary   Edwards      mary.edwards@example.com      US

In [15]:
# import cProfile
# import dis
#
# def loop_append():
#     res = []
#     for i in range(10):
#         res.append(i)
#     return res
#
# def list_comp():
#     return [i for i in range(10)]
#
# dis.dis(loop_append)

In [ ]:
type(fake.first_name())

In [ ]:
dir(fake.first_name())