In [90]:
import pandas as pd
import numpy as np
from faker import Faker
#import datetime
import random

In [91]:
## Creating class

fake = Faker()

In [92]:
## Reading files

tr_04_08 = pd.read_csv('../seeds/input_data/transaction_04_08_2025.csv')
tr_11_08 = pd.read_csv('../seeds/input_data/transaction_11_08_2025.csv')
tr_17_08 = pd.read_csv('../seeds/input_data/transaction_17_08_2025.csv')
tr_25_08 = pd.read_csv('../seeds/input_data/transaction_25_08_2025.csv')

## Declaring variables

country_codes = ('UK', 'AU', 'US', 'CA', 'DE')
referral_source_values = ("google_ads", "organic",  "social_media",
     "referral", "partner" )

In [93]:
#tr_04_08.columns

In [94]:
all_files_df = pd.concat([
    tr_04_08, tr_11_08,
    tr_17_08, tr_25_08
])

## Replace it after finishing transformation

# all_files_df = pd.concat([
#     tr_04_08[['user_id']], tr_11_08[[['user_id']],
#     tr_17_08[['user_id']], tr_25_08[['user_id']]
# ])

In [95]:
all_files_df.head()

,transaction_id,sender_account_id,receiver_account_id,transaction_amount,transaction_timestamp,transaction_type,payment_channel,merchant_category,transaction_status,currency,...,recipient_verified,recipient_account_age_days,recipient_country,latitude,longitude,city,country,ip_country,RecipientGNNScore,is_fraud
0,TXN000000062,ACC0044877,ACC0108626,3355.25,05/08/2025 22:47,P2M,Debit Card,Utilities,Success,INR,...,1,3439,India,17.386227,78.481575,Hyderabad,India,India,NaN,0
1,TXN000000145,ACC0113978,ACC0070986,360.68,07/08/2025 09:20,P2P,UPI,Shopping,Success,INR,...,1,973,India,13.099636,80.267209,Chennai,India,India,NaN,0
2,TXN000000195,ACC0051949,ACC0003579,890.78,09/08/2025 12:02,P2M,UPI,Utilities,Success,INR,...,1,1912,India,23.027151,72.581682,Ahmedabad,India,India,NaN,0
3,TXN000000218,ACC0017916,ACC0044510,3571.38,08/08/2025 23:15,P2P,RTGS,Salary,Success,INR,...,1,727,India,18.513034,73.864665,Pune,India,India,NaN,0
4,TXN000000224,ACC0012180,ACC0025048,4771.63,08/08/2025 07:09,P2M,NEFT,Restaurant,Success,INR,...,1,1771,India,18.525395,73.846750,Pune,India,India,NaN,0

In [96]:
## Df for transformation
res_df = all_files_df[['user_id']]
len_res_df = len(res_df)

In [97]:
#res_df['first_name'] = [fake.first_name() for _ in range(len_res_df)]

In [98]:
## Generating names with faker
res_df[['first_name', 'last_name']] = [
    (fake.first_name(), fake.last_name())
    for _ in range(len_res_df)
]

In [99]:
res_df.head()

     user_id first_name last_name
0  USR034397    Krystal  Williams
1  USR087541    Matthew      King
2  USR039823    Zachary   Leonard
3  USR013741     Jeremy    Hansen
4  USR009352     Sheryl     Gibbs

In [100]:
## Generating emails according to name

res_df['email'] = res_df['first_name'].str.lower() + '.'\
                   + res_df['last_name'].str.lower() + '@example.com'

In [101]:
## Generating dates with pandas

dates = pd.date_range("2023/01/01", "2024/01/01")
res_df["signup_date"] = pd.Series(dates).sample(n=len_res_df, replace=True).values
res_df["signup_date"] = [random.choice(dates) for _ in range(len_res_df)]

In [102]:
## Generating country and source with random

res_df['country'] = [random.choice(country_codes) for _ in range(len_res_df)]

In [105]:
## Generating source with numpy (the cheapest way)

res_df['referral_source'] = np.random.choice(referral_source_values, size = len_res_df)

In [106]:
res_df.head()

,user_id,first_name,last_name,email,signup_date,country,referral_source
0,USR034397,Krystal,Williams,krystal.williams@example.com,2023-05-23,AU,social_media
1,USR087541,Matthew,King,matthew.king@example.com,2023-04-06,UK,organic
2,USR039823,Zachary,Leonard,zachary.leonard@example.com,2023-05-20,DE,partner
3,USR013741,Jeremy,Hansen,jeremy.hansen@example.com,2023-12-27,UK,organic
4,USR009352,Sheryl,Gibbs,sheryl.gibbs@example.com,2023-07-07,UK,organic